vich_uploader:
    db_driver: orm

    mappings:
       products:
           uri_prefix: 'product_Lien'
           upload_destination: '%kernel.project_dir%/public/assets/img'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
           delete_on_update: false
           delete_on_remove: false
